# Generated by Django 2.2.2 on 2019-06-08 17:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('user_name', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=64)),
                ('tel', models.CharField(max_length=32)),
                ('email', models.CharField(max_length=64)),
                ('user_type', models.CharField(choices=[('ADMIN', 'ADMIN'), ('PARENT', 'PARENT'), ('ORG', 'ORGANIZATION'), ('TEA', 'TEACHER')], max_length=16)),
            ],
        ),
        migrations.CreateModel(
            name='EduOrg',
            fields=[
                ('user_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='api_server.Account')),
                ('org_code', models.CharField(max_length=64)),
                ('org_address', models.CharField(max_length=128)),
                ('org_contact', models.CharField(max_length=64)),
                ('org_introduction', models.TextField()),
                ('edu_field', models.CharField(max_length=64)),
                ('edu_age', models.PositiveIntegerField()),
                ('qualified', models.CharField(choices=[('Y', 'YSE'), ('N', 'NO')], max_length=16)),
            ],
        ),
        migrations.CreateModel(
            name='Parent',
            fields=[
                ('user_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='api_server.Account')),
                ('child_name', models.CharField(max_length=64)),
                ('child_birthday', models.DateField()),
                ('child_gender', models.CharField(choices=[('M', 'MALE'), ('F', 'FEMALE')], max_length=16)),
                ('parent_name', models.CharField(max_length=64)),
                ('parent_contact', models.CharField(max_length=64)),
                ('course_field', models.CharField(max_length=64)),
                ('course_cost', models.PositiveIntegerField()),
                ('course_place', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='SysAdmin',
            fields=[
                ('user_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='api_server.Account')),
                ('page_item_count', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('user_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='api_server.Account')),
                ('tea_name', models.CharField(max_length=64)),
                ('tea_gender', models.CharField(choices=[('M', 'MALE'), ('F', 'FEMALE')], max_length=16)),
                ('tea_birthday', models.DateField()),
                ('tea_id_number', models.CharField(max_length=64)),
                ('tea_contact', models.CharField(max_length=64)),
                ('tea_introduction', models.TextField()),
                ('edu_field', models.CharField(max_length=64)),
                ('edu_year', models.PositiveIntegerField()),
                ('edu_age', models.PositiveIntegerField()),
                ('qualified', models.CharField(choices=[('Y', 'YSE'), ('N', 'NO')], max_length=16)),
            ],
        ),
    ]
